#配置服务器
server:
  port: 80
#配置spring
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    name: quaint
    url: jdbc:mysql://127.0.0.1:3306/quaintblog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #时间转换处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #配置javaMail
  mail:
    #host: smtp.qq.com  个人
    host: smtp.exmail.qq.com  #企业
    #端口号465或587
    port: 587
    #username: your_qq_num@qq.com
    #password: your_licenseKey_or_password
    username: quaint@quaint-aini.com
    password: mGAxt233vKD6Grkn
    protocol: smtp
    default-encoding: UTF-8
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quaint.blog.pojo
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
    page-size-zero: true
